### ISSUE TITLE
Crashes with "from __future__ import print_function"

### ISSUE THREAD

**Issue by mhubig** [docopt/docopt#133]
Hi @halst,

found a bug today. docopt crashes with this example. But if you remove the `from __future__ import print_function` primer, all works fine.

``` python
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from __future__ import print_function
from docopt import docopt

"""HTML Cleaner.

Usage:
  cleanup [-p | --pretty] <element> <replacement> <filename>
  cleanup (-h | --help)
  cleanup (-V | --version)

Options:
  -h --help     Show this screen.
  -p --pretty   Prettify the output.
  -V --version  Show version.

"""
if __name__ == '__main__':
    arguments = docopt(__doc__, version='0.1.0')
    print(arguments)
```

Here is the traceback I get. Im using python 2.7.5

``` bash
$ python test.py
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    arguments = docopt(__doc__, version='0.1.0')
  File "/Users/markus/Development/hp/ENV/lib/python2.7/site-packages/docopt.py", line 558, in docopt
    DocoptExit.usage = printable_usage(doc)
  File "/Users/markus/Development/hp/ENV/lib/python2.7/site-packages/docopt.py", line 466, in printable_usage
    usage_split = re.split(r'([Uu][Ss][Aa][Gg][Ee]:)', doc)
  File "/Users/markus/Development/hp/ENV/lib/python2.7/re.py", line 173, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or buffer
```

**Comment by j-funk** [comment]
Just ran into this - grateful for the thread.
