### ISSUE TITLE
DocoptLanguageError for option without its comment string

### ISSUE THREAD

**Issue by pakal** [docopt/docopt#282]
We've had a weird bug when forgetting the comment following the "-v, --verbose", in the docopt string below. 

Isn't that allowed, to leave options without further comments when they're obvious (eg. -h, --help) ?
Would it be possible to have a more explicit error, if not ?

Here is the whole traceback:

Traceback (most recent call last):
  File "selenium_probe_launcher.py", line 16, in <module>
    options = docopt(__doc__)
  File "C:\Python34\lib\site-packages\docopt.py", line 560, in docopt
    pattern = parse_pattern(formal_usage(DocoptExit.usage), options)
  File "C:\Python34\lib\site-packages\docopt.py", line 373, in parse_pattern
    result = parse_expr(tokens, options)
  File "C:\Python34\lib\site-packages\docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "C:\Python34\lib\site-packages\docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "C:\Python34\lib\site-packages\docopt.py", line 413, in parse_atom
    result = pattern(*parse_expr(tokens, options))
  File "C:\Python34\lib\site-packages\docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "C:\Python34\lib\site-packages\docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "C:\Python34\lib\site-packages\docopt.py", line 415, in parse_atom
    raise tokens.error("unmatched '%s'" % token)
docopt.DocoptLanguageError: unmatched '['

```python
#! /usr/bin/env python3

"""Usage:
  selenium_prob_launcher.py [-v]

Options:
  -v, --verbose

Example:
  blabla alalal

"""

from docopt import docopt

options = docopt(__doc__)
```

**Comment by keleshev** [comment]
Thanks for the bug report—this is not an expected behavior.

**Comment by sigmapie8** [comment]
it works if you make the following changes:
 selenium_prob_launcher.py [<-v>] 
notice the <>
