### ISSUE TITLE
Options can't be documented twice 

### ISSUE THREAD

**Issue by ChloeTigre** [docopt/docopt#303]
In 0.6.2. This could be a dupe of #287 but I'm not sure.

Following docstring causes mayhem

```
boto/cli/create_ec2.py: do magic with boto

Usage:
    create_ec2.py --profile=PROFILE --name=INSTANCE_NAME --instance-type=INSTANCE_TYPE
        --key-name=KEY_NAME
        --ami=AMI_NAME --subnet=SUBNET_NAME
        --iam-instance-profile=IAM_INSTANCE_PROFILE
        [--security-group=SECURITY_GROUP]...
        [--elb=ELB_NAME]...
        [(--tag-name=STRING --tag-value=VALUE)]...

Options:
    -P PROFILE --profile=PROFILE                            profile in which to operate
    -n NAME --name=NAME                                     element name
    -T KEY --tag-name=KEY                                   tag name
    -V VALUE--tag-value=VALUE                               tag value
    -e ELB_NAME --elb=ELB_NAME                              name of ELB to register an instance with
    -a AMI_NAME --ami=AMI_NAME                              name of AMI to install an instance with
    -t TYPE --instance-type=TYPE                            instance type to create instance with
    -k KEY_NAME --key-name=KEY_NAME                         name of key that grants access to instance
    -s SUBNET_NAME --subnet=SUBNET_NAME                      subnet name to create instance in
    -S SG_NAME --security-group=SG_NAME                     security group to set to the instance
    -p PROFILE_NAME --iam-instance-profile=PROFILE_NAME     IAM instance profile to start instance with

```

Traceback:

```
Traceback (most recent call last):
  File "create_ec2.py", line 38, in <module>
    main()
  File "create_ec2.py", line 34, in main
    arguments = docopt.docopt(__doc__) #, options_first=True)
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 560, in docopt
    pattern = parse_pattern(formal_usage(DocoptExit.usage), options)
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 373, in parse_pattern
    result = parse_expr(tokens, options)
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 413, in parse_atom
    result = pattern(*parse_expr(tokens, options))
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 421, in parse_atom
    return parse_long(tokens, options)
  File "/home/chloe/venv/aws/lib/python3.4/site-packages/docopt.py", line 312, in parse_long
    (long, ', '.join(o.long for o in similar)))
docopt.DocoptLanguageError: --key-name is not a unique prefix: --key-name, --key-name?
```

My workaround is to include a non-breaking space (compose key and double-space) in the docstring before each Options line but this isn't exactly a solution as this merely masks options from docopt.

IMO Options should be able to be documented in the appropriate section even if they are specified in the usage line.

**Comment by ChloeTigre** [comment]
Another defect this incurs is that we cannot specify short options this way.

**Comment by ChloeTigre** [comment]
Another workaround is to put the Usage on a single line. This is ugly when rendered but it allows to keep synonymous short options.

**Comment by cobhimself** [comment]
Any update on this issue? I'm experiencing the same thing.
