### ISSUE TITLE
Crash on repeatable short-form flags

### ISSUE THREAD

**Issue by anka-213** [docopt/docopt#347]
The following usage string crashes the script:

    Usage:
          crash -ab...

Try it [here](http://try.docopt.org/?doc=Usage%3A%0D%0A++++++++crash+-ab...&argv=)

**Comment by anka-213** [comment]
Here is the traceback:

```
Traceback (most recent call last):
  File "app.py", line 33, in run_docopt
    sys.stdout.write(json.dumps(docopt(doc, argv), sort_keys=True,
  File "/app/.heroku/python/lib/python2.7/site-packages/docopt.py", line 576, in docopt
    matched, left, collected = pattern.fix().match(argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/docopt.py", line 233, in match
    matched, l, c = p.match(l, c)
  File "/app/.heroku/python/lib/python2.7/site-packages/docopt.py", line 233, in match
    matched, l, c = p.match(l, c)
  File "/app/.heroku/python/lib/python2.7/site-packages/docopt.py", line 256, in match
    assert len(self.children) == 1
AssertionError
```
