### ISSUE TITLE
Misleading error message: unmatched '(' when actual error is unwanted pipe

### ISSUE THREAD

**Issue by alexwlchan** [docopt/docopt#388]
Python 3.6.1, docopt 0.6.2.

If I run the following example:

```python
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
"""
Usage:
  example.py -h | --help

Options:
  -h | --help           Show this screen.
"""

import docopt

docopt.docopt(__doc__)
```

I get the following traceback:

```
Traceback (most recent call last):
  File "example.py", line 13, in <module>
    docopt.docopt(__doc__)
  File "/Users/chana/.virtualenvs/tempenv-4a6b200392dfd/lib/python3.6/site-packages/docopt.py", line 560, in docopt
    pattern = parse_pattern(formal_usage(DocoptExit.usage), options)
  File "/Users/chana/.virtualenvs/tempenv-4a6b200392dfd/lib/python3.6/site-packages/docopt.py", line 373, in parse_pattern
    result = parse_expr(tokens, options)
  File "/Users/chana/.virtualenvs/tempenv-4a6b200392dfd/lib/python3.6/site-packages/docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "/Users/chana/.virtualenvs/tempenv-4a6b200392dfd/lib/python3.6/site-packages/docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "/Users/chana/.virtualenvs/tempenv-4a6b200392dfd/lib/python3.6/site-packages/docopt.py", line 415, in parse_atom
    raise tokens.error("unmatched '%s'" % token)
docopt.DocoptLanguageError: unmatched '('
```

The actual problem is that docopt doesn’t like the pipe character in the options list – if I remove that, everything works fine. But the error message could be more helpful – telling me about an unmatched parens when there isn’t one in my code makes it hard to find the error!

**Comment by myd7349** [comment]
Try this:
```python
"""
Usage:
  example.py -h | --help

Options:
  -h --help           Show this screen.
"""
```

**Comment by ernstki** [comment]
Similarly

```
[(-i|--infile FILE) | TERM...]
```

works, wheras:

```
[(-i|--infile) FILE | TERM...]
```

causes the `docopt.DocoptLanguageError: unmatched '('` error and backtrace.

But fortunately this issue at least led me in the direction of looking at the pipe vs. parenthesis placement, rather than just giving up. So thanks!
