### ISSUE TITLE
Windows installation fails

### ISSUE THREAD

**Issue by wjsetzer** [docopt/docopt#453]
Python: 3.7.3
Platform: Windows 10

When installing with pip, fails with error:
```
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\wjsetzer\AppData\Local\Temp\pip-install-4g490b59\docopt\setup.py", line 3, in <module>
        from docopt import __version__
    ModuleNotFoundError: No module named 'docopt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\wjsetzer\AppData\Local\Temp\pip-install-4g490b59\docopt\
```

**Comment by sukiletxe** [comment]
Cannot reproduce with Cpython 3.7.2.

**Comment by wjsetzer** [comment]
Bugged Python install. Fixed with reinstalling Python.
