### ISSUE TITLE
Error not unique prefix when options are in multiple lines

### ISSUE THREAD

**Issue by unixsurfer** [docopt/docopt#472]
Having the following causes error below, but if I put all options in one line I don't get the error. why is that? I prefer to have the options in  multiple lines as having them in one-line make the usage unreadable.

```
"""A wrapper for rally.

Usage:
    myrally gen-track-params --bulk=BULK-SIZE... --clients=CLIENTS... --directory=PATH
                             [-d] --challenges=CHALLENGES... --shards=SHARDS...
                             --logging-volume=SIZE --replicas=REPLICAS --track=TRACK

Arguments
    BULK-SIZE       The bulk sizes to use
    CLIENTS         The number of clients
    CHALLENGES      The name of challenges
    SHARDS          The number of shards per replica
    SIZE            The size of the daily logging volume
    PATH            A directory path to store generated track parameters
    REPLICAS        The number of replicas
    TRACK           The name of the track

    CONFIG-FILE     A configuration file with various parameters
    TAG             The tag name to set for the rally run



Options:
    --bulk=BULK-SIZE            Set the bulk size
    --clients=CLIENTS           Set the number of clients
    --challenges=CHALLENGES     Set the name of the challenge
    -d --dry-run                Print generated configuration without writing it
    --directory=PATH            Set the base directory to store configuration
    --logging-volume=SIZE       Set the daily logging volume size
    --replicas=REPLICAS         Set the number of replicas
    --shards=SHARDS             Set the shard size
    --track=TRACK               Set track name

Note:
    Options that are mentioned with ellipsis(...) can be set multiple times, for
    instance: -b 1 -b 2. This creates an array with values with the some order as they
    are passed, so the value `1` is first and the value `2` is second.
"""
```

```
myrally --help
Traceback (most recent call last):
  File "/home/pparissis/.virtualenvs/py3.5/bin/myrally", line 10, in <module>
    sys.exit(main())
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/myrally/cli.py", line 50, in main
    args = docopt(__doc__, version=VERSION)
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 560, in docopt
    pattern = parse_pattern(formal_usage(DocoptExit.usage), options)
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 373, in parse_pattern
    result = parse_expr(tokens, options)
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 413, in parse_atom
    result = pattern(*parse_expr(tokens, options))
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 381, in parse_expr
    seq = parse_seq(tokens, options)
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 396, in parse_seq
    atom = parse_atom(tokens, options)
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 421, in parse_atom
    return parse_long(tokens, options)
  File "/home/pparissis/.virtualenvs/py3.5/lib/python3.5/site-packages/docopt.py", line 312, in parse_long
    (long, ', '.join(o.long for o in similar)))
docopt.DocoptLanguageError: --track is not a unique prefix: --track, --track?
```

**Comment by unixsurfer** [comment]
I found a workaround! I placed at the begging of each line an optional option
```

Usage:
    myrally gen-track-params --bulk=BULK-SIZE... --clients=CLIENTS...
                             [--directory=PATH] --challenges=CHALLENGES... --track=TRACK
                             [-d] --shards=SHARDS... --logging-volume=SIZE --replicas=REPLICAS

```
