### ISSUE TITLE
Can't install in ComfyUI

### ISSUE THREAD

**Issue by NoOne511** [docopt/docopt#525]
I need docopt for some addons in ComfyUI (https://github.com/comfyanonymous/ComfyUI) and when I try to install it via cmd it gives me this error

`Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting docopt==0.6.2
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\me\AppData\Local\Temp\pip-install-objy3ll9\docopt_1d44c09cb8fc47bb94830068c8fd6e60\setup.py", line 3, in <module>
          from docopt import __version__
      ModuleNotFoundError: No module named 'docopt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

using 

`pip install --target M:\AI-SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages docopt==0.6.2`

I tried to fix the "python setup.py egg_info did not run successfully" with those fixes (https://www.easeus.com/data-recovery/python-setup-py-egg-info-failed-with-error-code-1.html) with no avail.

**Comment by NoOne511** [comment]
Solved by installing from wheel: https://www.piwheels.org/project/docopt/
